// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.coffeeshop.domain;

import com.springsource.roo.coffeeshop.domain.Menu;
import com.springsource.roo.coffeeshop.domain.MenuDataOnDemand;
import com.springsource.roo.coffeeshop.domain.MenuIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MenuIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MenuIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MenuIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MenuIntegrationTest: @Transactional;
    
    @Autowired
    MenuDataOnDemand MenuIntegrationTest.dod;
    
    @Test
    public void MenuIntegrationTest.testCountMenus() {
        Assert.assertNotNull("Data on demand for 'Menu' failed to initialize correctly", dod.getRandomMenu());
        long count = Menu.countMenus();
        Assert.assertTrue("Counter for 'Menu' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MenuIntegrationTest.testFindMenu() {
        Menu obj = dod.getRandomMenu();
        Assert.assertNotNull("Data on demand for 'Menu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Menu' failed to provide an identifier", id);
        obj = Menu.findMenu(id);
        Assert.assertNotNull("Find method for 'Menu' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Menu' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MenuIntegrationTest.testFindAllMenus() {
        Assert.assertNotNull("Data on demand for 'Menu' failed to initialize correctly", dod.getRandomMenu());
        long count = Menu.countMenus();
        Assert.assertTrue("Too expensive to perform a find all test for 'Menu', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Menu> result = Menu.findAllMenus();
        Assert.assertNotNull("Find all method for 'Menu' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Menu' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MenuIntegrationTest.testFindMenuEntries() {
        Assert.assertNotNull("Data on demand for 'Menu' failed to initialize correctly", dod.getRandomMenu());
        long count = Menu.countMenus();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Menu> result = Menu.findMenuEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Menu' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Menu' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MenuIntegrationTest.testFlush() {
        Menu obj = dod.getRandomMenu();
        Assert.assertNotNull("Data on demand for 'Menu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Menu' failed to provide an identifier", id);
        obj = Menu.findMenu(id);
        Assert.assertNotNull("Find method for 'Menu' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMenu(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Menu' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MenuIntegrationTest.testMergeUpdate() {
        Menu obj = dod.getRandomMenu();
        Assert.assertNotNull("Data on demand for 'Menu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Menu' failed to provide an identifier", id);
        obj = Menu.findMenu(id);
        boolean modified =  dod.modifyMenu(obj);
        Integer currentVersion = obj.getVersion();
        Menu merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Menu' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MenuIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Menu' failed to initialize correctly", dod.getRandomMenu());
        Menu obj = dod.getNewTransientMenu(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Menu' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Menu' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Menu' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MenuIntegrationTest.testRemove() {
        Menu obj = dod.getRandomMenu();
        Assert.assertNotNull("Data on demand for 'Menu' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Menu' failed to provide an identifier", id);
        obj = Menu.findMenu(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Menu' with identifier '" + id + "'", Menu.findMenu(id));
    }
    
}
