// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.coffeeshop.domain;

import com.springsource.roo.coffeeshop.domain.EmployeeDataOnDemand;
import com.springsource.roo.coffeeshop.domain.OrdersDataOnDemand;
import com.springsource.roo.coffeeshop.domain.Receipt;
import com.springsource.roo.coffeeshop.domain.ReceiptDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ReceiptDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ReceiptDataOnDemand: @Component;
    
    private Random ReceiptDataOnDemand.rnd = new SecureRandom();
    
    private List<Receipt> ReceiptDataOnDemand.data;
    
    @Autowired
    EmployeeDataOnDemand ReceiptDataOnDemand.employeeDataOnDemand;
    
    @Autowired
    OrdersDataOnDemand ReceiptDataOnDemand.ordersDataOnDemand;
    
    public Receipt ReceiptDataOnDemand.getNewTransientReceipt(int index) {
        Receipt obj = new Receipt();
        setDates(obj, index);
        setReceiptID(obj, index);
        setStatus(obj, index);
        setTimes(obj, index);
        return obj;
    }
    
    public void ReceiptDataOnDemand.setDates(Receipt obj, int index) {
        Date Dates = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDates(Dates);
    }
    
    public void ReceiptDataOnDemand.setReceiptID(Receipt obj, int index) {
        String ReceiptID = "ReceiptID_" + index;
        obj.setReceiptID(ReceiptID);
    }
    
    public void ReceiptDataOnDemand.setStatus(Receipt obj, int index) {
        Boolean Status = Boolean.TRUE;
        obj.setStatus(Status);
    }
    
    public void ReceiptDataOnDemand.setTimes(Receipt obj, int index) {
        String Times = "Times_" + index;
        obj.setTimes(Times);
    }
    
    public Receipt ReceiptDataOnDemand.getSpecificReceipt(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Receipt obj = data.get(index);
        Long id = obj.getId();
        return Receipt.findReceipt(id);
    }
    
    public Receipt ReceiptDataOnDemand.getRandomReceipt() {
        init();
        Receipt obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Receipt.findReceipt(id);
    }
    
    public boolean ReceiptDataOnDemand.modifyReceipt(Receipt obj) {
        return false;
    }
    
    public void ReceiptDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Receipt.findReceiptEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Receipt' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Receipt>();
        for (int i = 0; i < 10; i++) {
            Receipt obj = getNewTransientReceipt(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
