// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.coffeeshop.domain;

import com.springsource.roo.coffeeshop.domain.Receipt;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Receipt_Roo_Configurable {
    
    declare @type: Receipt: @Configurable;
    
}
